# This is a basic workflow to help you get started with Actions

name: deploy to heroku

# Controls when the workflow will run
on: 
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    
    - uses: extractions/netrc@v1
      with:
        machine: git.heroku.com
        username: ${{ secrets.HEROKU_EMAIL }}
        password: ${{ secrets.HEROKU_API_KEY }}

    - uses: extractions/netrc@v1
      with:
        machine: api.heroku.com
        username: ${{ secrets.HEROKU_EMAIL }}
        password: ${{ secrets.HEROKU_API_KEY }}

    - name: Add remote front
      run: git remote add heroku-front https://git.heroku.com/vincula-front.git

    - name: Add remote back
      run: git remote add heroku-back https://git.heroku.com/vincula-back.git

    # Runs a single command using the runners shell
    - name: Deploy front to Heroku
      run: make deploy-front
      
    - name: Deploy back to Heroku
      run: make deploy-back
